/* Copyright 2018 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
// This file is generated by generate-test-list.ts
import {AudioComponent} from './tests/audio/audio.component';
import {DisplayComponent} from './tests/display/display.component';

const TEST_COMPONENTS = {
  Audio: AudioComponent,
  Display: DisplayComponent
};

export {TEST_COMPONENTS};
