/* Copyright 2018 The Chromium OS Authors. All rights reserved.
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */
// This file is generated by generate-test-list.ts
import {TestResource} from './interfaces/test-resource';
import {AudioComponent} from './tests/audio/audio.component';
import {DisplayComponent} from './tests/display/display.component';
import {
  DISPLAY_ARGS_SPEC
} from './tests/display/display.component';
import {TouchscreenComponent} from './tests/touchscreen/touchscreen.component';
import {
  TOUCHSCREEN_ARGS_SPEC
} from './tests/touchscreen/touchscreen.component';

const TEST_COMPONENTS: {[testName: string]: TestResource} = {
  Audio: {
    component: AudioComponent,
    argsSpec: []
  },
  Display: {
    component: DisplayComponent,
    argsSpec: DISPLAY_ARGS_SPEC
  },
  Touchscreen: {
    component: TouchscreenComponent,
    argsSpec: TOUCHSCREEN_ARGS_SPEC
  }
};

export {TEST_COMPONENTS};
