#!/bin/sh
# Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

MYDIR="$(dirname "$(readlink -f "$0")")"
FACTORY_BASE="/usr/local/factory"
IPTABLESD="${FACTORY_BASE}/init/iptables.d"

is_freon() {
  # Currently we only install frecon on freon boards.
  if [ -x "/sbin/frecon" ]; then
    return 0
  else
    return 1
  fi
}

main() {
  # For freon boards: We disable powerd in factory test mode, but the screen
  # backlight is turned on by powerd. Manually set the brightness level to
  # 50% of max brightness.
  if is_freon; then
    backlight_tool --set_brightness_percent=50.0
  fi

  # Load iptables rules
  for rule_file in ${IPTABLESD}/*.sh; do
    "$rule_file"
  done

  # Install console (VT2) customizations
  mount --bind "${MYDIR}/profile.d/vt2.sh" /etc/profile.d/cursor.sh

  for tag_file in ${MYDIR}/tag_*; do
    local tag_script="${MYDIR}/tags.d/start_${tag_file#${MYDIR}/tag_}"
    if [ -x "${tag_script}" ]; then
      "${tag_script}"
    fi
  done

  local tag_presenter="${MYDIR}/run_goofy_presenter"
  local tag_device="${MYDIR}/run_goofy_device"

  if [ -f "${tag_presenter}" ]; then
    # Presenter-only or standalone mode.
    mount --bind "${MYDIR}/etc/presenter.conf" /etc/chrome_dev.conf
  elif [ ! -f "${tag_device}" ]; then
    # Monolithic mode.
    mount --bind "${MYDIR}/etc/chrome_dev.conf" /etc/chrome_dev.conf
  fi
}

main "$@"
