#!/bin/sh
# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
SCRIPT_BASE="$(readlink -f "$(dirname "$0")")"
FACTORY_LOG_FILE=/var/log/factory.log

start_factory() {
  echo "
    Starting factory program...

    If you don't see factory window after more than one minute,
    try to switch to VT2 (Ctrl-Alt-F2), log in, and check the messages by:
      tail $FACTORY_LOG_FILE

    If it keeps failing, try to reset by:
      $SCRIPT_BASE/restart.sh -a
  "

  # Preload modules here
  modprobe i2c-dev 2>/dev/null || true

  # This script should be located in .../autotest/cros/factory.
  cd "$SCRIPT_BASE/../.."
  eval "$("$SCRIPT_BASE/startx.sh")"
  "$SCRIPT_BASE/goofy.py" >>"$FACTORY_LOG_FILE" 2>&1
}

stop_factory() {
  # Try to kill X, and any other Python scripts, five times.
  echo -n "Stopping factory."
  for i in $(seq 5); do
    pkill 'X|python' || break
    sleep 1
    echo -n "."
  done

  echo "

    Factory tests terminated. To check error messages, try
      tail $FACTORY_LOG_FILE

    To restart, press Ctrl-Alt-F2, log in, and type:
      $SCRIPT_BASE/restart.sh

    If restarting does not work, try to reset by:
      $SCRIPT_BASE/restart.sh -a
    "
}

case "$1" in
  "start" )
    start_factory "$@"
    ;;

  "stop" )
    stop_factory "$@"
    ;;

  * )
    echo "Usage: $0 [start|stop]"
    exit 1
    ;;
esac
