#!/bin/sh
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

MYDIR="$(dirname $(readlink -f $0))"
PYTHONPATH=$MYDIR/py_pkg $MYDIR/py/hwid_tool.py "$@"
