FROM python:2.7.13-alpine

ARG workdir="/usr/src/app"
ARG cros_src_dir="${workdir}"/cros/src
ARG chromeos_hwid_dir="${cros_src_dir}"/platform/chromeos-hwid
ARG regions_dir="${cros_src_dir}"/platform2/regions
ARG factory_dir="${cros_src_dir}"/platform/factory
ARG hwid_service_docker_dir="${factory_dir}"/py/hwid/service/docker_env
WORKDIR "${workdir}"

RUN apk upgrade --no-cache && \
    apk add --no-cache git py-pip python && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir PyYaml==3.12

# The build context should be in the CROS src dir.
ADD platform/chromeos-hwid "${chromeos_hwid_dir}"
ADD platform2/regions "${regions_dir}"
ADD platform/factory/py "${factory_dir}"/py
ADD platform/factory/py_pkg "${factory_dir}"/py_pkg

ENV CROS_WORKON_SRCROOT "${workdir}"/cros

RUN ln -s "${hwid_service_docker_dir}"/service_manager.py \
    /usr/bin/service_manager

CMD ["/usr/bin/service_manager", "--local-test", "--update-minutes", "1"]
