#!/usr/bin/env bash
# Copyright 2020 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

echo "${FAKE_RUNTIME_PROBE_STDOUT}"
echo "$@" >&2
exit "${FAKE_RUNTIME_PROBE_RETURN_CODE}"
