#!/bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a stub that simulates minijail0, without running process in jail.
# Strip parameters (-*) and stop if -- was found.
while [ "$1" != "${1#-}" ]; do
  if [ "$1" = "--" ]; then
    # exec accepts "--", no need to shift again.
    break
  else
    shift
  fi
done

exec "$@"
