# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = []

  operations = [
      migrations.CreateModel(
          name='BoardModel',
          fields=[
              ('name', models.CharField(
                  max_length=200, primary_key=True, serialize=False)),
              ('url', models.URLField()),
          ],
          options={
              'ordering': ['name'],
          },),
  ]
