# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [('backend', '0001_initial'),]

  operations = [
      migrations.RenameModel(
          old_name='BoardModel',
          new_name='Board',),
  ]
