# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 08:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [('backend', '0003_auto_20160905_0631'),]

  operations = [
      migrations.AddField(
          model_name='board',
          name='umpire_enabled',
          field=models.BooleanField(default=True)),
      migrations.AlterField(
          model_name='board',
          name='umpire_enabled',
          field=models.BooleanField(default=False)),
      migrations.RenameField(
          model_name='board', old_name='host', new_name='umpire_host'),
      migrations.RenameField(
          model_name='board', old_name='port', new_name='umpire_port'),
      migrations.AlterField(
          model_name='board',
          name='umpire_host',
          field=models.GenericIPAddressField(null=True)),
      migrations.AlterField(
          model_name='board',
          name='umpire_port',
          field=models.PositiveIntegerField(null=True)),
      migrations.AlterField(
          model_name='board',
          name='name',
          field=models.CharField(
              max_length=200,
              primary_key=True,
              serialize=False,
              validators=[django.core.validators.RegexValidator(
                  message=b'Slashes are not allowed in board name',
                  regex=b'[^/]+')]))
  ]
