# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [('backend', '0004_auto_20160927_0855'),]

  operations = [
      migrations.CreateModel(
          name='TemporaryUploadedFile',
          fields=[
              ('id', models.AutoField(
                  auto_created=True,
                  primary_key=True,
                  serialize=False,
                  verbose_name='ID')),
              ('file', models.FileField(upload_to=b'%Y%m%d')),
              ('created', models.DateTimeField(auto_now_add=True)),
          ],),
  ]
