# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [('backend', '0005_temporaryuploadedfile'),]

  operations = [
      migrations.AlterField(
          model_name='board',
          name='name',
          field=models.CharField(
              max_length=200, primary_key=True, serialize=False),),
  ]
