# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-03 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0008_domeconfig'),
  ]

  operations = [
      migrations.RenameModel(
          old_name='Board',
          new_name='Project',
      ),
  ]
