# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0009_auto_20170803_0625'),
  ]

  operations = [
      migrations.AddField(
          model_name='project',
          name='netboot_bundle',
          field=models.CharField(max_length=200, null=True),),
  ]
