# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-30 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0010_project_netboot_bundle'),
  ]

  operations = [
      migrations.AddField(
          model_name='project',
          name='umpire_version',
          field=models.PositiveIntegerField(null=True),
      ),
  ]
