# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-15 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0011_project_umpire_version'),
  ]

  operations = [
      migrations.AlterField(
          model_name='project',
          name='umpire_host',
          field=models.CharField(max_length=128, null=True),
      ),
  ]
