# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-16 07:04
from __future__ import unicode_literals

import backend.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0012_auto_20180515_0642'),
  ]

  operations = [
      migrations.AlterField(
          model_name='temporaryuploadedfile',
          name='file',
          field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=b'/tmp/shared'), upload_to=backend.models.GenerateUploadToPath),
      ),
  ]
