# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-12 06:03
from __future__ import unicode_literals

import backend.models
import django.core.files.storage
from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0013_auto_20180516_0704'),
  ]

  operations = [
      migrations.AlterField(
          model_name='temporaryuploadedfile',
          name='file',
          field=backend.models.TemporaryUploadedFileField(storage=django.core.files.storage.FileSystemStorage(location='/tmp/shared'), upload_to=backend.models.GenerateUploadToPath),
      ),
  ]
