# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-09-20 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0014_auto_20180612_0603'),
  ]

  operations = [
      migrations.RemoveField(
          model_name='project',
          name='umpire_host',
      ),
  ]
