# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-10-08 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0015_remove_project_umpire_host'),
  ]

  operations = [
      migrations.RemoveField(
          model_name='project',
          name='umpire_version',
      ),
  ]
