# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2020-04-10 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('backend', '0016_remove_project_umpire_version'),
  ]

  operations = [
      migrations.AddField(
          model_name='domeconfig',
          name='mroute_enabled',
          field=models.BooleanField(default=False),
      ),
  ]
