# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2021-01-05 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_domeconfig_mroute_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domeconfig',
            old_name='mroute_enabled',
            new_name='mcast_enabled',
        ),
    ]
